### ISSUE TITLE
Support For Apollo Server 2.0

### ISSUE THREAD

**Issue by stolinski** [apollographql/meteor-integration#123]
Upgrading to apollo-server-express 2 breaks this package.

**Comment by lorensr** [comment]
I can't keep up with you, Scott. That's not even out yet! 🏃‍♂️

**Comment by StorytellerCZ** [comment]
It is current now! :rocket:
https://www.npmjs.com/package/apollo-server?activeTab=versions

**Comment by lorensr** [comment]
@evans do you know the right way to connect Apollo Server 2.0 with Meteor's [`WebApp.connectHandlers.use`](https://docs.meteor.com/packages/webapp.html)?

Old way:

```js
const app = express();
app.use(
    '/graphql',
    bodyParser.json(),
    graphqlExpress(...)
)
WebApp.connectHandlers.use(app);
```

Now I'm trying this:

```js
import { ApolloServer } from 'apollo-server-express'

const apollo = new ApolloServer({
  typeDefs,
  resolvers
})

const app = express()

apollo.applyMiddleware({ app, path: '/graphql' })

WebApp.connectHandlers.use(app)
```

Which gets me Playground at localhost:3000/graphql, but gives this error on server:

```
E20180720-23:41:42.195(-4) (webapp_server.js:900) Error running template: Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.setWriteHeadHeaders (/Users/me/.meteor/packages/webapp/.1.6.2.evbchg.9x99f++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/on-headers/index.js:82:19)
    at ServerResponse.writeHead (/Users/me/.meteor/packages/webapp/.1.6.2.evbchg.9x99f++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/on-headers/index.js:41:36)
    at getBoilerplateAsync.then (packages/webapp/webapp_server.js:892:13)
    at /Users/me/.meteor/packages/promise/.0.11.1.1a124lx.neui++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20180720-23:41:42.197(-4)? (STDERR) (node:42342) UnhandledPromiseRejectionWarning: Error: Can't set headers after they are sent.
W20180720-23:41:42.197(-4)? (STDERR)     at validateHeader (_http_outgoing.js:491:11)
W20180720-23:41:42.198(-4)? (STDERR)     at ServerResponse.setHeader (_http_outgoing.js:498:3)
W20180720-23:41:42.198(-4)? (STDERR)     at ServerResponse.setWriteHeadHeaders (/Users/me/.meteor/packages/webapp/.1.6.2.evbchg.9x99f++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/on-headers/index.js:82:19)
W20180720-23:41:42.198(-4)? (STDERR)     at ServerResponse.writeHead (/Users/me/.meteor/packages/webapp/.1.6.2.evbchg.9x99f++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/on-headers/index.js:41:36)
W20180720-23:41:42.198(-4)? (STDERR)     at getBoilerplateAsync.then.catch.error (packages/webapp/webapp_server.js:901:13)
W20180720-23:41:42.198(-4)? (STDERR)     at /Users/me/.meteor/packages/promise/.0.11.1.1a124lx.neui++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20180720-23:41:42.199(-4)? (STDERR) (node:42342) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an asyncfunction without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
```

https://github.com/lorensr/test-meteor-apollo

**Comment by lorensr** [comment]
Published `apollo@3.0.0`. New API, where you create the server and client instances yourself. Updated docs here:

https://github.com/apollographql/apollo-client/blob/lorensr/update-meteor-docs/docs/source/recipes/meteor.md

**Comment by Type1J** [comment]
That's a dead link.

**Comment by lorensr** [comment]
The branch has been merged. It's now on the docs site:

https://www.apollographql.com/docs/react/recipes/meteor.html

**Comment by tab00** [comment]
I think this issue was closed prematurely. [Subscriptions](https://www.apollographql.com/docs/react/recipes/meteor.html#Subscriptions) section of the documentation still needs to be updated.
