### ISSUE TITLE
Error: Cannot find module './client'

### ISSUE THREAD

**Issue by elie222** [apollographql/meteor-integration#88]
```
W20170317-01:14:26.099(2)? (STDERR) /Users/Elie/.meteor/packages/meteor-tool/.1.4.3_2.1yeevzn++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170317-01:14:26.100(2)? (STDERR) 						throw(ex);
W20170317-01:14:26.100(2)? (STDERR) 						^
W20170317-01:14:26.100(2)? (STDERR)
W20170317-01:14:26.101(2)? (STDERR) Error: Cannot find module './client'
W20170317-01:14:26.101(2)? (STDERR)     at require (packages/modules-runtime.js:123:19)
W20170317-01:14:26.102(2)? (STDERR)     at meteorInstall.node_modules.subscriptions-transport-ws.dist.index.js (packages/modules.js:28956:10)
W20170317-01:14:26.103(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170317-01:14:26.103(2)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
W20170317-01:14:26.103(2)? (STDERR)     at Module.Mp.import (/Users/Elie/.meteor/packages/modules/.0.7.9.8gle5++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
W20170317-01:14:26.103(2)? (STDERR)     at meteorInstall.node_modules.meteor.apollo.src.main-client.js (packages/apollo/src/main-client.js:1:434)
W20170317-01:14:26.104(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170317-01:14:26.104(2)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
W20170317-01:14:26.105(2)? (STDERR)     at Module.Mp.import (/Users/Elie/.meteor/packages/modules/.0.7.9.8gle5++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
W20170317-01:14:26.105(2)? (STDERR)     at meteorInstall.node_modules.meteor.apollo.src.main-server.js (packages/apollo/src/main-server.js:1:75)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

But this issue may be related to upgrading Meteor to the latest version (to 1.4.3.2).

**Comment by xavcz** [comment]
Oh, weird! 

On which versions of `subscriptions-transport-ws` are you? Which versions of Node / NPM?

**Comment by xavcz** [comment]
Mmh, just updated to Meteor 1.4.3.2, and not having the problem 🤔 

What's your implementation of `meteor/apollo` ? If you could make a simple reproduction with a git repo, that would be awesome 🌮

**Comment by xavcz** [comment]
@elie222 quick check, did you:
```
npm install subscriptions-transport-ws graphql-subscriptions
```
?

**Comment by elie222** [comment]
Yes I did. I haven't had a look at it for the last few days. I just
reverted back to the previous meteor version for now.

**Comment by xavcz** [comment]
Ok, it should be good if you update & install these node packages. Closing for now, feel free to re-open with a reproduction if you encounter this bug 👍

**Comment by aaroncalderon** [comment]
I just upgraded one of my projects to meteor 1.4.3.2 and I had the same error message. I think my problem was that I had not installed `graphql-subscriptions`.
