### ISSUE TITLE
Error: Can't find npm module 'on-headers'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?

### ISSUE THREAD

**Issue by rschiavi** [apollographql/meteor-integration#95]
Tried everything I can think of. working meteor app, then not working. did meteor npm install ., etc.

Any ideas?

W20170412-16:03:15.461(-7)? (STDERR) Error: Can't find npm module 'on-headers'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20170412-16:03:15.461(-7)? (STDERR)     at Object.require (/Users/rich/dev/sirenas/kraken/.meteor/local/build/programs/server/boot.js:200:17)
W20170412-16:03:15.462(-7)? (STDERR)     at options.fallback (packages/modules-runtime.js:458:18)
W20170412-16:03:15.463(-7)? (STDERR)     at require (packages/modules-runtime.js:117:16)
W20170412-16:03:15.463(-7)? (STDERR)     at meteorInstall.node_modules.morgan.index.js (packages/modules.js:8843:17)
W20170412-16:03:15.464(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:188:9)
W20170412-16:03:15.465(-7)? (STDERR)     at require (packages/modules-runtime.js:111:16)
W20170412-16:03:15.466(-7)? (STDERR)     at meteorInstall.app.js (app.js:4:14)
W20170412-16:03:15.466(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:188:9)
W20170412-16:03:15.467(-7)? (STDERR)     at require (packages/modules-runtime.js:111:16)
W20170412-16:03:15.467(-7)? (STDERR)     at /Users/rich/dev/sirenas/kraken/.meteor/local/build/programs/server/app/app.js:8475:1
=> Exited with code: 1

**Comment by rschiavi** [comment]
and if i try a meteor build, then a cd bundle/program/server; npm install .  and node bundle/main.js get this:

Error: Can't find npm module 'etag'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?

**Comment by rschiavi** [comment]
and a clean start over....something feels wonky

Security context: 0x341c35ab4629 <JS Object>
    1: mark [/Users/rich/.meteor/packages/ecmascript/.0.7.2.a0ile2++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-generator/lib/source-map.js:~59] [pc=0x30da8fb1177b] (this=0x2185b3a64fc9 <a SourceMap with map 0x1b48d5da87b9>,generatedLine=92598,generatedColumn=23,line=28275,column=5720,identifierName=0x341c35a04101 <null>,file...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

**Comment by xavcz** [comment]
I don't know any Apollo related package using this `on-headers`. 

What version of `meteor/apollo` are you using?
What versions of the Apollo node packages are you using?
Do you have a reproduction in a repository? 🙏

**Comment by xavcz** [comment]
Closing for inactivity. Feel free to re-open if you hit this bug again.
